#pragma config(Motor,  port1,           rightmotors,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           leftmotors,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bVexAutonomousMode = false;
	while(1 == 1)
	{
		//motor[leftmotors] = 63;
		//motor[rightmotors] = 63;
		motor[leftmotors] = vexRT[Ch3];
		motor[rightmotors] = vexRT[Ch2];
	}
}
