#pragma config(Motor,  port1,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bVexAutonomousMode = false;
	while (1 == 1)
	{
		if (vexRT[Ch2] < -63)
		{
			motor[rightFront] = -63;
			motor[rightBack] = -63;
		}
		else {
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];
	}
		if (vexRT[Ch3] < -63)
		{
			motor[leftFront] = -63;
			motor[leftBack] = -63;
		}
		else {
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];
	}

	}
}
