#pragma config(Sensor, in3,    back_limit_switch, sensorTouch)
#pragma config(Sensor, in4,    front_limit_switch, sensorTouch)
#pragma config(Sensor, in5,    pneumatic_1,    sensorDigitalOut)
#pragma config(Sensor, in9,    pneumatic_lift, sensorDigitalOut)
#pragma config(Sensor, in10,   pneumatic_lift, sensorDigitalOut)
#pragma config(Sensor, in11,   pneumatic_lift, sensorDigitalOut)
#pragma config(Sensor, in12,   pneumatic_lift, sensorDigitalOut)
#pragma config(Sensor, in15,   pneumatic_cannon, sensorDigitalOut)
#pragma config(Motor,  port1,           left_front,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           right_front,   tmotorVex393, openLoop)
#pragma config(Motor,  port3,           right_back,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           left_back,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           cannon,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bVexAutonomousMode = false;

	while(1 == 1)
	{
		//motor[left_front] = 0;
		//motor[left_back] = 0;
		//motor[right_front] = 127;
		//motor[right_back] = 127;

		//motor[right_back] = vexRT(Ch2);
		//motor[right_front] = vexRT(Ch2);
		//motor[left_back] = vexRT(Ch1);
		//motor[left_front] = vexRT(Ch1);

	//Following is arcade drive
		 motor[right_front] = vexRT[Ch3]/2 - vexRT[Ch4]/2;		//y-axis value: forward/backward motion
		motor[left_front] = vexRT[Ch3]/2 + vexRT[Ch4]/2;
		motor[right_back] = vexRT[Ch3]/2 - vexRT[Ch4]/2;
		motor[left_back] = vexRT[Ch3]/2 + vexRT[Ch4]/2;

	//Following is mecanum drive
		//motor[right_front] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		//motor[right_back] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
		//motor[left_front] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		//motor[left_back] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];

		motor[cannon] = vexRT[Ch2]; // movement of cannon up and down

	//SensorValue[pneumatic_cannon] = vexRT[btn6U] / 127;

if (vexRT[Ch6] == 127)
		{
			SensorValue[pneumatic_cannon] = 0;
		}
else	if (vexRT[Ch6] == 0)
		{
			SensorValue[pneumatic_cannon] = 1;
		}



	}
}
